### ISSUE TITLE
Configure Personal Options for Assistant

### ISSUE THREAD

**Issue by nickbrandl** [MicrosoftDocs/dynamics-365-ai#23]
In the Assistant doc page located here [assistant.md](https://github.com/MicrosoftDocs/dynamics-365-ai/blob/master/ai-docs/sales/assistant.md), the steps described under header [Enable and configure the action cards](https://github.com/MicrosoftDocs/dynamics-365-ai/blob/master/ai-docs/sales/assistant.md#enable-and-configure-the-action-cards-that-are-most-helpful-for-you ) do not work. I'm able to see in the personal options a link to configure Sales AI cards but not all admins are able to do so, and regular users don't see the link either.
As per the icon to configure those cards in the Assistant, I cannot see it neither with my user nor regular user.

**Comment by udaykirang** [comment]
Thanks for your feedback, nick. we are looking into the issue and will fix it.

**Comment by udaykirang** [comment]
@nickbrandl, the topic is updated with latest information.

Thanks,
Uday
